housedatabig=read.csv("Housingwithbig.csv")

#factors for data set 1
housedatabig$furnishingstatus <- factor(housedatabig$furnishingstatus,levels=c(0,1,2), labels=c("unfurnished","semi-furnished","furnished"))
housedatabig$guestroom<-factor(housedatabig$guestroom,levels=c(0,1),labels=c("No","Yes"))
housedatabig$mainroad<-factor(housedatabig$mainroad,levels=c(0,1),labels=c("No","Yes"))
housedatabig$basement<-factor(housedatabig$basement,levels=c(0,1),labels=c("No","Yes"))
housedatabig$hotwaterheating<-factor(housedatabig$hotwaterheating,levels=c(0,1),labels=c("No","Yes"))
housedatabig$airconditioning<-factor(housedatabig$airconditioning,levels=c(0,1),labels=c("No","Yes"))
housedatabig$prefarea<-factor(housedatabig$prefarea,levels=c(0,1),labels=c("No","Yes"))
housedatabig$big<-factor(housedatabig$big,levels=c(0,1,2),labels=c("Small","Medium","Large"))
#set appropriate variables as factor variables


#set reference levels to reduce dimensionality of factor variables

housedatabig$mainroad=relevel(housedatabig$mainroad, "No")
housedatabig$guestroom=relevel(housedatabig$guestroom, "No")
housedatabig$basement=relevel(housedatabig$basement, "No")
housedatabig$hotwaterheating=relevel(housedatabig$hotwaterheating, "No")
housedatabig$airconditioning=relevel(housedatabig$airconditioning, "No")
housedatabig$prefarea=relevel(housedatabig$prefarea, "No")
housedatabig$furnishingstatus=relevel(housedatabig$furnishingstatus, "unfurnished")
housedatabig$big=relevel(housedatabig$big, "Small")


#install.packages("tidyverse")
#install.packages("caret")

library(tidyverse)
library(caret)

train_control <- trainControl(method = "repeatedcv", number = 10, repeats =9, savePredictions = "final")
model <- train(price~.,data=housedatabig, method = "lm", trControl = train_control)
print(model)
logmodel <- train(log(price)~area+stories+mainroad+guestroom+basement+hotwaterheating+airconditioning+parking+prefarea+furnishingstatus+big ,data=housedatabig, method = "lm", trControl = train_control)
print(logmodel)
#i could export this possibly?
exp(predict(logmodel))

interactions_model <- train(price~area+bedrooms+bathrooms+mainroad+guestroom+basement+
                              hotwaterheating+airconditioning+parking+prefarea+furnishingstatus+
                              big+area*bathrooms+area*guestroom+area*basement+area*hotwaterheating+
                              bedrooms*hotwaterheating+bedrooms*hotwaterheating+bathrooms*hotwaterheating+
                              bathrooms*airconditioning+bathrooms*parking+bathrooms*prefarea+
                              bathrooms*furnishingstatus+stories*big+mainroad*hotwaterheating+
                              mainroad*prefarea+guestroom*basement+guestroom*airconditioning+
                              guestroom*parking+guestroom*prefarea+basement*hotwaterheating+
                              basement*airconditioning+hotwaterheating*airconditioning+
                              airconditioning*parking+airconditioning*furnishingstatus+
                              furnishingstatus*big+hotwaterheating*furnishingstatus+
                              parking*big, data=housedatabig, method = "lm", trControl = train_control)

print(interactions_model)

#takes the numbers in prediction vector generated by model
p_linear <- model$pred$pred

str(model$pred)

#to exponentiate log values i need to calculate rmse by hand:

#true values extracted from observations vector
y_true <- model$pred$obs
#calculation using formula of root mean square error
rmse_linear <- sqrt(mean((p_linear - y_true)^2))
rmse_linear

#extract prediction numbers from log model and then exponentiate
p <- logmodel$pred$pred
p_exp <- exp(p)
#also exponentiate the observations so RMSE scales properly
obs_exp <- exp(logmodel$pred$obs)
str(logmodel$pred)

rmse_log_exp <- sqrt(mean((p_exp - obs_exp)^2))
rmse_log_exp
#exponentiating r^2
log_ss_res = sum(((exp(logmodel$pred$obs) - exp(logmodel$pred$pred)^2)))
log_y_obs_mean = mean(logmodel$pred$obs)
log_ss_tot = sum(((exp(logmodel$pred$obs) - exp(log_y_obs_mean))^2))


#res = exp(log_ss_res)
#tot = exp(log_ss_tot)
logexprsquared = 1 - (log_ss_res / log_ss_tot)
logexprsquared
res/tot


#test
pdat <- logmodel$pred
pred_avg <- aggregate(pred~rowIndex, data=pdat, FUN=mean)
obs_once <- aggregate(obs ~ rowIndex, data=pdat, FUN = function(x) x[1])
merged <- merge(pred_avg,obs_once, by="rowIndex")
str(merged)
mergedpredexp <- exp(merged$pred)
mergedobsexp <- exp(merged$obs)

ss_res = sum((mergedobsexp - mergedpredexp)^2)
ss_tot = sum((mergedobsexp - mean(mergedobsexp))^2)
r2_log = 1 - (ss_res / ss_tot)
r2_log
